sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-us-west-1.aliyuncs.com
    access-key-id: LTAI5tADvqLKixtxA4pmUeGr
    access-key-secret: TVp2KG7ih7HDovUByg4N5CjmmKyoxy
    bucket-name: sky-take-out-image-storage
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    app-id: wx7ec8b80df401ed43
    secret: 56106a6e37394e97ddaff9ff0881fdb9m
#    mchid:
#    mchSerialNo:
#    privateKeyFilePath:
#    apiV3Key:
#    weChatPayCertFilePath:
#    notifyUrl:
#    refundNotifyUrl: